name: tomato_schedule
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  intl: ^0.18.1
  date_picker_timeline: ^1.2.5
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit/Kanit-Black.ttf
          weight: 900
